### PR TITLE
Fix database migrations to v11

### LINKED ISSUE #653: [BUG] v11 DB Migration fails when migrating from SHIELD 8.5.0 or earlier
**Describe the bug**
We accidentally deleted the `healthy` member of the jobs table in schema v6. We accidentally added it back for v6 in 8.6.0. If the user has already migrated past this point, they won't get the fix, and the migration to v11 will fail because of the missing `healthy` column.

**To Reproduce**
1. Deploy 8.5.0
2. Migrate to 8.6.0

**Expected behavior**
Should have migrated cleanly.

**Screenshots**

**SHIELD versions (please complete the following information):**
 - SHIELD Core: 8.6.0
 - SHIELD CLI: n/a

**Browser version(s) (please complete if reporting a web UI bug):**
n/a

**Additional context**

### PR DESCRIPTION
**Pull request by sriniketh923**
This pr should fix #653, #654 and #656 . I tested the database migration locally by using the code from 8.5.0 and then upgrading it and it works fine.

### CODE REVIEW

File: db/schema_v11.go [hunk 1]
```diff
@@ -7,31 +7,31 @@ func (s v11Schema) Deploy(db *DB) error {
...
-	               keep_n             INTEGER NOT NULL DEFAULT 0,
-	               keep_days          INTEGER NOT NULL DEFAULT 0,
-	               next_run           INTEGER DEFAULT 0,
-	               priority           INTEGER DEFAULT 50,
-	               paused             BOOLEAN NOT NULL DEFAULT 0,
-	               fixed_key          INTEGER DEFAULT 0,
-	               healthy            BOOLEAN NOT NULL DEFAULT 0
-	             )`)
+			        uuid               UUID PRIMARY KEY,
+					target_uuid        UUID NOT NULL,
```
Comment (thomasmitchell) [inline db/schema_v11.go]: This formatting is borked.

**Comment by thomasmitchell** [comment]
Additionally, because the targets being marked as failed with no jobs thing was pre-existing (and there may be existing migrations to schema 11 because it was borked in 5.6.0), we need to make a fixup that patches that up for existing entries.

**Comment by thomasmitchell** [comment]
It also needs to have some handling in 11 either way, because you can't get to 12 if you can't finish 11.

**Comment by sriniketh923** [comment]
I just took out "j.healthy" in v11 and set the default health to 0, which should make the migration from v10 to v11 pass. In v12 all the migrations of the database should be fixed. Even the targets are set to healthy by default and is set to false only when it sees an unhealthy job. So even if a target has no jobs, it should be healthy.

File: db/schema_v11.go [hunk 2]
```diff
@@ -44,6 +44,15 @@ func (s v11Schema) Deploy(db *DB) error {
 		return err
 	}
 
+	jobs, err := db.GetAllJobs(&JobFilter{})
```
Comment (thomasmitchell) [inline db/schema_v11.go]: This is redundant. Put it only in v12.

File: db/schema_v12.go [hunk 3]
```diff
@@ -0,0 +1,115 @@
...
+
+import "fmt"
+
+type v12Schema struct{}
+
+func (s v12Schema) Deploy(db *DB) error {
+	var err error
+
+	// set the tenant_uuid column to NOT NULL
+	err = db.Exec(`CREATE TABLE jobs_new (
```
Comment (thomasmitchell) [inline db/schema_v12.go]: why do we add this table in both 12 and 11?

File: db/schema_v12.go [hunk 4]
```diff
@@ -0,0 +1,76 @@
...
+
+	jobs, err := db.GetAllJobs(&JobFilter{})
+	if err != nil {
+		return nil
+	}
+	for _, job := range jobs {
+		healthy := job.LastTaskStatus == "done"
+		db.UpdateJobHealth(job.UUID, healthy)
+	}
+	tenant := RandomID()
```
Comment (jhunt) [inline db/schema_v12.go]: Why are we setting a random UUID as a default for targets?

Comment (sriniketh923) [reply db/schema_v12.go]: I was running the tests for targets and the tests fail because the UUID was not assigned. I was also looking at the schema_v4 and saw that tennant_uuid is set to a random UUID as a default.
